import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';

const Policy: React.FC = () => {
  return (
    <ScrollView 
    showsVerticalScrollIndicator={false}
    style={styles.container}>


        <View>

  <Text style={styles.header}>Noosk Privacy Policy</Text>
  
  <Text style={styles.subHeader}>Introduction</Text>
  <Text>Noosk (“we,” “our,” or “us”) is committed to protecting your privacy.</Text>
  
  <Text style={styles.subHeader}>1. Definitions and Key Terms</Text>
<View style={styles.listContainer}>
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Cookie:</Text> small amount of data generated by a website and saved by your web browser.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Company:</Text> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Noosk, Inc., 1209 Orange Street, Wilmington (DE), 19801 that is responsible for your information under this Privacy Policy.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Country:</Text> where Noosk or the owners/founders of Noosk are based, in this case is United States.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Customer:</Text> refers to the company, organization or person that signs up to use the Noosk Service to manage the relationships with your consumers or service users.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Device:</Text> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Noosk and use the services.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>IP address:</Text> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Personnel:</Text> refers to those individuals who are employed by Noosk or are under contract to perform a service on behalf of one of the parties.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Personal Data:</Text> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Service:</Text> refers to the service provided by Noosk as described in the relative terms (Terms of Use – include link to terms of use) and on this platform.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Third-party service:</Text> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Website:</Text> Noosk's site, which can be accessed via this URL: www.noosk.co</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>You:</Text> a person or entity that is registered with Noosk to use the Services.</Text >
</View>
  
<Text style={styles.subHeader}>2. What Information Do We Collect?</Text>
<Text>We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</Text>
<View style={styles.listContainer}>
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Name / Username</Text></Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Email Addresses</Text></Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Age</Text></Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Password</Text></Text >
</View>

{"\n"}
{"\n"}

<Text> {"\n"} We also collect information from mobile devices for a better user experience, although these features are completely optional:</Text>
<View style={styles.listContainer}>
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Camera (Pictures and Videos):</Text> Granting camera permission allows the user to upload any picture or video straight from the website, you can safely deny camera permissions for this website.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>Photo Gallery (Pictures and Videos):</Text> Granting photo and video gallery access allows the user to upload any picture or video from their photo and video gallery, you can safely deny photo gallery access for this website.</Text >
</View>

<Text style={styles.subHeader}>3. How Do We Use The Information We Collect?</Text>
<Text>Any of the information we collect from you may be used in one of the following ways:</Text>
<View style={styles.listContainer}>
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>To personalize your experience:</Text> your information helps us to better respond to your individual needs.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>To improve our website:</Text> we continually strive to improve our website offerings based on the information and feedback we receive from you.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>To improve customer service:</Text> your information helps us to more effectively respond to your customer service requests and support needs.</Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>To process transactions</Text></Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>To administer a contest, promotion, survey or other site feature</Text></Text >
  <Text style={styles.bulletText}><Text style={styles.bulletTitle}><Text>• </Text>To send periodic emails</Text></Text >
</View>

<Text style={styles.subHeader}>4. When does Noosk use end user information from third parties?</Text>
<Text>Noosk will collect End User Data necessary to provide the Noosk services to our customers.</Text>
<Text>End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</Text>

<Text style={styles.subHeader}>5. When does Noosk use customer information from third parties?</Text>
<Text>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Noosk customer, we receive information from a third party that provides automated fraud detection services to Noosk. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</Text>

<Text style={styles.subHeader}>6. Do we share the information we collect with third parties?</Text>
<Text>We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.</Text>

<View style={styles.listContainer}>
  <Text style={styles.bulletText}>We may engage trusted third-party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.</Text >
  <Text style={styles.bulletText}>We may share portions of our log file data for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website in a shared location, and type of the device used to visit the website. They may aggregate information about our advertising and what you see on the website and then provide auditing, research and reporting for us and our advertisers.</Text >
</View>

<Text style={styles.subHeader}>7. Where and when is information collected from customers and end users?</Text>
<Text>Noosk will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.</Text>
<Text style={styles.subHeader}>8. How Do We Use Your Email Address?</Text>
<Text>By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</Text>

<Text style={styles.subHeader}>9. How Long Do We Keep Your Information?</Text>
<Text>We keep your information only so long as we need it to provide the Noosk Service to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and anyone who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.</Text>

<Text style={styles.subHeader}>10. How Do We Protect Your Information?</Text>
<Text>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Noosk or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.</Text>

<Text style={styles.subHeader}>11. Analytics</Text>
<Text>We may use third-party Service providers to monitor and analyze the use of our Service.</Text>

<Text style={styles.subsubHeader}>Google Analytics</Text>
<Text>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</Text>

<Text>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.</Text>

<Text>For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a href="https://policies.google.com/privacy">https://policies.google.com/privacy</a></Text>

<Text style={styles.subHeader}>12. Could my information be transferred to other countries?</Text>
<Text>Noosk is incorporated in United States. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.</Text>

<Text style={styles.subHeader}>13.	Is the information collected through the Noosk Service secure?</Text>
<Text>We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.</Text>

<Text style={styles.subHeader}>14. Can I update or correct my information?</Text>
<Text>The rights you have to request updates or corrections to the information Noosk collects depend on your relationship with Noosk. Personnel may update or correct their information as detailed in our internal company employment policies.</Text>
<Text>Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.</Text>
<Text>You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system...</Text>

<Text style={styles.subHeader}>15. Personnel</Text>
<Text>If you are a Noosk worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.</Text>
<Text>You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you.</Text>

<Text style={styles.subHeader}>16. Sale of Business</Text>
<Text>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of Noosk or any of its Corporate Affiliates (as defined herein), or that portion of Noosk or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.</Text>

<Text style={styles.subHeader}>17. Affiliates</Text>
<Text>We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with Noosk, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.</Text>

<Text style={styles.subHeader}>18. Governing Law</Text>
<Text>This Privacy Policy is governed by the laws of United States without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.</Text>

<Text style={styles.subHeader}>19. Your Consent</Text>
<Text>We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.</Text>

<Text style={styles.subHeader}>20. Links to Other Websites</Text>
<Text>This Privacy Policy applies only to the Services offered by Noosk. Noosk may contain links to other websites not operated or controlled by Noosk. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us.</Text>

<Text style={styles.subHeader}>21. Cookies</Text>
<Text>Noosk uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use.</Text>

<Text style={styles.subHeader}>22. Blocking and disabling cookies and similar technologies</Text>
<Text>Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services.</Text>

<Text style={styles.subHeader}>23. Kids' Privacy</Text>
<Text>We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.</Text>

<Text style={styles.subHeader}>24. Changes To Our Privacy Policy</Text>
<Text>We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.</Text>


<Text style={styles.subHeader}>25. Third-Party Services</Text>
<Text>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").</Text>
<Text>You acknowledge and agree that Noosk shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Noosk does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</Text>
<Text>Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</Text>

<Text style={styles.subHeader}>Information about General Data Protection Regulation (GDPR)</Text>
<Text>We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under protection from being replicated or used in the wrong way.</Text>

<Text style={styles.subsubHeader}>What is GDPR?</Text>
<Text>GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and enhances the control the EU residents have, over their personal data.The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our customers’ data is important irrespective of where they are located, which is why we have implemented GDPR controls as our baseline standard for all our operations worldwide.</Text>

<Text style={styles.subsubHeader}>What is personal data?</Text>
<Text>Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity.
</Text>
<Text>The Data Protection Principles include requirements such as:</Text>
<Text>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.
Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.
Personal data should be held no longer than necessary to fulfil its purpose.
People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</Text>


<Text style={styles.subsubHeader}>Why is GDPR important?</Text>
<Text>GDPR adds some new requirements regarding how companies should protect individuals' personal data that they collect and process. It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond these facts it's simply the right thing to do. At Noosk we strongly believe that your data privacy is very important and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation.</Text>

<Text style={styles.subsubHeader}>Individual Data Subject's Rights - Data Access, Portability and Deletion</Text>
<Text>We are committed to helping our customers meet the data subject rights requirements of GDPR. Noosk processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.

We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove personal data. We got you! We've been set up as self-service from the start and have always given you access to your data and your customers data. Our customer support team is here for you to answer any questions you might have about working with the API.

To request a copy of your data, please send us an email at info@noosk.co</Text>

<Text style={styles.subHeader}>California Residents</Text>
<Text>The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</Text>

<Text>We are also required to communicate information about rights California residents have under California law. </Text>
    
<Text>You may exercise the following rights:</Text>

<View style={styles.listContainer}>
<Text style={styles.bulletText}>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</Text >
<Text style={styles.bulletText}>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</Text >
<Text style={styles.bulletText}>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</Text >
<Text style={styles.bulletText}>RIght to Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</Text >
<Text style={styles.bulletText}>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</Text >
</View>

<Text>We do not sell the Personal Information of our users.

For more information about these rights, please contact us.</Text>

<Text style={styles.subHeader}>California Online Privacy Protection Act (CalOPPA)</Text>
<Text>CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</Text>

<Text>CalOPPA users have the following rights:</Text>

<View style={styles.listContainer}>
<Text style={styles.bulletText}>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</Text >
<Text style={styles.bulletText}>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</Text >
<Text style={styles.bulletText}>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</Text >
<Text style={styles.bulletText}>RIght to Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</Text >
<Text style={styles.bulletText}>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</Text >
</View>

<Text>We do not sell the Personal Information of our users.

For more information about these rights, please contact us.</Text>

<Text style={styles.subHeader}>Contact Us</Text>

<Text>Don't hesitate to contact us if you have any questions.

Via Email: info@noosk.co </Text>



</View>

      

        

      {/* Repeat for other sections */}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 10,
  },
  header: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  subHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 10,
  },
  subsubHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 10,
  },
  lists: {

  },
  sectionContainer:{
    flexDirection: "column",
  },
  listContainer:{

  },
  bulletText:{

  },
  bulletTitle: {
    fontWeight: "bold",
    flexDirection: "row",
  }
  // Add more styles as needed
});

export default Policy;
